version: '3.1'
services:
  mysql-standalone:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myproject
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql-container:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - user-mysql
  myproject-container:
    image: tuananhdoroy/myproject
    build: .
    depends_on:
      - mysql-standalone
    ports:
      - 8888:8888
    restart: always
    networks:
      - user-mysql
networks:
  user-mysql:
    driver: bridge